'use strict';

exports.send_xml = function(req, res) {
	var builder = require('xmlbuilder');
	var doc = builder.create('root')
	  .ele('soapenv:Envelope')
	  .att('xmlns:soapenv', 'http://schemas.xmlsoap.org/soap/envelope/')
	  .ele('soapenv:Body')
	    .ele('xsd:businessToClientMsgRequest')
	      .ele('partner')
	      .txt(req.body.partner)
	      .up()
	    .ele('interchange')
	    .att('msg_type','elsinfov1')
	      .ele('header')
	      .att('sender_cd',req.body.sender_cd)
	      .up()
	      .ele('item_list')
		.ele('item')
		.att('service',req.body.service)
		  .ele('add_service')
		    .ele('option')
		    .att('code','GN')
		    .up()
		    .ele('option')
		    .att('code','GM')
		    .up()
		  .up()
		  .ele('measures')
		  .att('weight','1')
		  .up()
		  .ele('receiverAddressee')
		    .ele('person_name')
		    .txt(req.body.receiverPersonName)
		    .up()
		    .ele('address')
		    .att('postcode',req.body.receiverPostcode)
		    .att('deliverypoint',req.body.receiverDeliveryPoint)
		    .att('country',req.body.receiverCountry)
		    .att('street',req.body.receiverStreet)
		    .up()
		  .up()
		  .ele('returnAddressee')
		    .ele('person_name')
		    .txt(req.body.returnPersonName)
		    .up()
		    .ele('mobile')
		    .txt(req.body.returnMobile)
		    .up()
		    .ele('address')
		    .att('postcode',req.body.returnPostcode)
		    .att('deliverypoint',req.body.returnDeliveryPoint)
		    .att('country',req.body.returnCountry)
		    .att('street',req.body.returnStreet)
		    .up()
		  .up() 
	.end({ pretty: true });	
	res.send(doc);

};
